version: "3.1"
services:
  db:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_PORT=${PGPORT}
      - PGHOST=/var/run/postgresql/
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - ./dbinit/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
